-- Criar tabela laboratorio_produtos
CREATE TABLE IF NOT EXISTS laboratorio_produtos (
  id SERIAL PRIMARY KEY,
  codigo VARCHAR(50) UNIQUE NOT NULL,
  nome VARCHAR(255) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inserir todos os 250 produtos
-- 🔬 EQUIPAMENTO (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-EQP-001', 'Microscópio óptico', '🔬 EQUIPAMENTO'),
('LAB-EQP-002', 'Microscópio binocular', '🔬 EQUIPAMENTO'),
('LAB-EQP-003', 'Microscópio eletrônico digital', '🔬 EQUIPAMENTO'),
('LAB-EQP-004', 'Centrífuga microclínica', '🔬 EQUIPAMENTO'),
('LAB-EQP-005', 'Banho-maria digital', '🔬 EQUIPAMENTO'),
('LAB-EQP-006', 'Incubadora bacteriológica', '🔬 EQUIPAMENTO'),
('LAB-EQP-007', 'Estufa de esterilização', '🔬 EQUIPAMENTO'),
('LAB-EQP-008', 'Autoclave vertical', '🔬 EQUIPAMENTO'),
('LAB-EQP-009', 'pH-metro digital', '🔬 EQUIPAMENTO'),
('LAB-EQP-010', 'Condutivímetro', '🔬 EQUIPAMENTO'),
('LAB-EQP-011', 'Espectrofotômetro UV-Vis', '🔬 EQUIPAMENTO'),
('LAB-EQP-012', 'Fotômetro de chama', '🔬 EQUIPAMENTO'),
('LAB-EQP-013', 'Refratômetro óptico', '🔬 EQUIPAMENTO'),
('LAB-EQP-014', 'Densímetro eletrônico', '🔬 EQUIPAMENTO'),
('LAB-EQP-015', 'Balança analítica de precisão', '🔬 EQUIPAMENTO'),
('LAB-EQP-016', 'Balança semianalítica', '🔬 EQUIPAMENTO'),
('LAB-EQP-017', 'Destilador de água', '🔬 EQUIPAMENTO'),
('LAB-EQP-018', 'Agitador magnético com placa aquecedora', '🔬 EQUIPAMENTO'),
('LAB-EQP-019', 'Agitador de tubos', '🔬 EQUIPAMENTO'),
('LAB-EQP-020', 'Vortex misturador', '🔬 EQUIPAMENTO'),
('LAB-EQP-021', 'Pipetador automático', '🔬 EQUIPAMENTO'),
('LAB-EQP-022', 'Micro-ondas para laboratório', '🔬 EQUIPAMENTO'),
('LAB-EQP-023', 'Chapa aquecedora elétrica', '🔬 EQUIPAMENTO'),
('LAB-EQP-024', 'Freezer -20°C', '🔬 EQUIPAMENTO'),
('LAB-EQP-025', 'Ultra freezer -80°C', '🔬 EQUIPAMENTO');

-- 🧫 VIDRARIA (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-VID-101', 'Béquer 50 mL', '🧫 VIDRARIA'),
('LAB-VID-102', 'Béquer 100 mL', '🧫 VIDRARIA'),
('LAB-VID-103', 'Béquer 250 mL', '🧫 VIDRARIA'),
('LAB-VID-104', 'Béquer 500 mL', '🧫 VIDRARIA'),
('LAB-VID-105', 'Béquer 1000 mL', '🧫 VIDRARIA'),
('LAB-VID-106', 'Erlenmeyer 125 mL', '🧫 VIDRARIA'),
('LAB-VID-107', 'Erlenmeyer 250 mL', '🧫 VIDRARIA'),
('LAB-VID-108', 'Erlenmeyer 500 mL', '🧫 VIDRARIA'),
('LAB-VID-109', 'Erlenmeyer 1000 mL', '🧫 VIDRARIA'),
('LAB-VID-110', 'Balão volumétrico 10 mL', '🧫 VIDRARIA'),
('LAB-VID-111', 'Balão volumétrico 25 mL', '🧫 VIDRARIA'),
('LAB-VID-112', 'Balão volumétrico 50 mL', '🧫 VIDRARIA'),
('LAB-VID-113', 'Balão volumétrico 100 mL', '🧫 VIDRARIA'),
('LAB-VID-114', 'Balão volumétrico 500 mL', '🧫 VIDRARIA'),
('LAB-VID-115', 'Balão volumétrico 1000 mL', '🧫 VIDRARIA'),
('LAB-VID-116', 'Cilindro graduado 10 mL', '🧫 VIDRARIA'),
('LAB-VID-117', 'Cilindro graduado 25 mL', '🧫 VIDRARIA'),
('LAB-VID-118', 'Cilindro graduado 50 mL', '🧫 VIDRARIA'),
('LAB-VID-119', 'Cilindro graduado 100 mL', '🧫 VIDRARIA'),
('LAB-VID-120', 'Cilindro graduado 500 mL', '🧫 VIDRARIA'),
('LAB-VID-121', 'Cilindro graduado 1000 mL', '🧫 VIDRARIA'),
('LAB-VID-122', 'Tubo de ensaio 13x100 mm', '🧫 VIDRARIA'),
('LAB-VID-123', 'Tubo de ensaio 16x150 mm', '🧫 VIDRARIA'),
('LAB-VID-124', 'Tubo de ensaio 20x200 mm', '🧫 VIDRARIA'),
('LAB-VID-125', 'Vidro de relógio 100 mm', '🧫 VIDRARIA');

-- 🧪 CONSUMÍVEL (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-CON-201', 'Papel filtro tipo A', '🧪 CONSUMÍVEL'),
('LAB-CON-202', 'Papel filtro tipo B', '🧪 CONSUMÍVEL'),
('LAB-CON-203', 'Papel filtro tipo C', '🧪 CONSUMÍVEL'),
('LAB-CON-204', 'Algodão hidrófilo em rama', '🧪 CONSUMÍVEL'),
('LAB-CON-205', 'Gaze estéril 10x10 cm', '🧪 CONSUMÍVEL'),
('LAB-CON-206', 'Gaze não-estéril 10x10 cm', '🧪 CONSUMÍVEL'),
('LAB-CON-207', 'Lenços desmaquiantes', '🧪 CONSUMÍVEL'),
('LAB-CON-208', 'Papel toalha branco', '🧪 CONSUMÍVEL'),
('LAB-CON-209', 'Papel toalha marrom', '🧪 CONSUMÍVEL'),
('LAB-CON-210', 'Papel milimetrado A4', '🧪 CONSUMÍVEL'),
('LAB-CON-211', 'Papel carbono preto', '🧪 CONSUMÍVEL'),
('LAB-CON-212', 'Fita adesiva isolante', '🧪 CONSUMÍVEL'),
('LAB-CON-213', 'Fita métrica 5 metros', '🧪 CONSUMÍVEL'),
('LAB-CON-214', 'Barbante branco rolo', '🧪 CONSUMÍVEL'),
('LAB-CON-215', 'Barbante preto rolo', '🧪 CONSUMÍVEL'),
('LAB-CON-216', 'Elástico sortido pct', '🧪 CONSUMÍVEL'),
('LAB-CON-217', 'Clipe de papel caixa', '🧪 CONSUMÍVEL'),
('LAB-CON-218', 'Colchete sortido pct', '🧪 CONSUMÍVEL'),
('LAB-CON-219', 'Trombone dourado pct', '🧪 CONSUMÍVEL'),
('LAB-CON-220', 'Trombone níquel pct', '🧪 CONSUMÍVEL'),
('LAB-CON-221', 'Tesoura escolar com ponta redonda', '🧪 CONSUMÍVEL'),
('LAB-CON-222', 'Tesoura ponta fina', '🧪 CONSUMÍVEL'),
('LAB-CON-223', 'Pinça de plástico', '🧪 CONSUMÍVEL'),
('LAB-CON-224', 'Pinça de metal cromada', '🧪 CONSUMÍVEL'),
('LAB-CON-225', 'Espátula plástica', '🧪 CONSUMÍVEL');

-- 🦺 EPI (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-EPI-301', 'Avental de algodão branco', '🦺 EPI'),
('LAB-EPI-302', 'Avental impermeável PVC', '🦺 EPI'),
('LAB-EPI-303', 'Avental de Tyvek descartável', '🦺 EPI'),
('LAB-EPI-304', 'Luva de látex pó M', '🦺 EPI'),
('LAB-EPI-305', 'Luva de látex pó G', '🦺 EPI'),
('LAB-EPI-306', 'Luva de látex pó GG', '🦺 EPI'),
('LAB-EPI-307', 'Luva de nitrila sem pó M', '🦺 EPI'),
('LAB-EPI-308', 'Luva de nitrila sem pó G', '🦺 EPI'),
('LAB-EPI-309', 'Luva de nitrila sem pó GG', '🦺 EPI'),
('LAB-EPI-310', 'Luva de látex alérgeno-free M', '🦺 EPI'),
('LAB-EPI-311', 'Luva de látex alérgeno-free G', '🦺 EPI'),
('LAB-EPI-312', 'Luva de couro', '🦺 EPI'),
('LAB-EPI-313', 'Óculos de proteção comum', '🦺 EPI'),
('LAB-EPI-314', 'Óculos de proteção com proteção lateral', '🦺 EPI'),
('LAB-EPI-315', 'Óculos de proteção 3D', '🦺 EPI'),
('LAB-EPI-316', 'Máscara N95', '🦺 EPI'),
('LAB-EPI-317', 'Máscara N100', '🦺 EPI'),
('LAB-EPI-318', 'Máscara PFF2', '🦺 EPI'),
('LAB-EPI-319', 'Máscara respiratória reutilizável', '🦺 EPI'),
('LAB-EPI-320', 'Escudo facial protetor', '🦺 EPI'),
('LAB-EPI-321', 'Touca descartável', '🦺 EPI'),
('LAB-EPI-322', 'Capuz de proteção', '🦺 EPI'),
('LAB-EPI-323', 'Perneira descartável', '🦺 EPI'),
('LAB-EPI-324', 'Cobre sapato descartável', '🦺 EPI'),
('LAB-EPI-325', 'Capote impermeável descartável', '🦺 EPI');

-- 🔬 ANÁLISE (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-ANA-401', 'Reagente para glicose 500mL', '🔬 ANÁLISE'),
('LAB-ANA-402', 'Reagente para colesterol 500mL', '🔬 ANÁLISE'),
('LAB-ANA-403', 'Reagente para triglicérides 500mL', '🔬 ANÁLISE'),
('LAB-ANA-404', 'Reagente para uréia 500mL', '🔬 ANÁLISE'),
('LAB-ANA-405', 'Reagente para creatinina 500mL', '🔬 ANÁLISE'),
('LAB-ANA-406', 'Reagente para ácido úrico 500mL', '🔬 ANÁLISE'),
('LAB-ANA-407', 'Reagente para proteína total 500mL', '🔬 ANÁLISE'),
('LAB-ANA-408', 'Reagente para albumina 500mL', '🔬 ANÁLISE'),
('LAB-ANA-409', 'Reagente para bilirrubina 500mL', '🔬 ANÁLISE'),
('LAB-ANA-410', 'Reagente para fosfatase alcalina 500mL', '🔬 ANÁLISE'),
('LAB-ANA-411', 'Reagente para AST/ALT 500mL', '🔬 ANÁLISE'),
('LAB-ANA-412', 'Reagente para GGT 500mL', '🔬 ANÁLISE'),
('LAB-ANA-413', 'Reagente para LDH 500mL', '🔬 ANÁLISE'),
('LAB-ANA-414', 'Reagente para cálcio 500mL', '🔬 ANÁLISE'),
('LAB-ANA-415', 'Reagente para fósforo 500mL', '🔬 ANÁLISE'),
('LAB-ANA-416', 'Reagente para ferro 500mL', '🔬 ANÁLISE'),
('LAB-ANA-417', 'Reagente para magnésio 500mL', '🔬 ANÁLISE'),
('LAB-ANA-418', 'Reagente para sódio 500mL', '🔬 ANÁLISE'),
('LAB-ANA-419', 'Reagente para potássio 500mL', '🔬 ANÁLISE'),
('LAB-ANA-420', 'Reagente para cloreto 500mL', '🔬 ANÁLISE'),
('LAB-ANA-421', 'Reagente para CO2 500mL', '🔬 ANÁLISE'),
('LAB-ANA-422', 'Reagente para amilase 500mL', '🔬 ANÁLISE'),
('LAB-ANA-423', 'Reagente para lipase 500mL', '🔬 ANÁLISE'),
('LAB-ANA-424', 'Reagente para PSA 500mL', '🔬 ANÁLISE'),
('LAB-ANA-425', 'Controle positivo/negativo frasco', '🔬 ANÁLISE');

-- 🧼 ESTERILIZAÇÃO (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-EST-501', 'Álcool 70% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-502', 'Álcool 90% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-503', 'Álcool iodado frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-504', 'Água destilada frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-505', 'Água destilada frasco 5L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-506', 'Água ultrapura frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-507', 'Solução fisiológica 0.9% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-508', 'Solução de formol 37-40% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-509', 'Solução de fenol frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-510', 'Solução de clorexidina frasco 500mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-511', 'Solução de iodo frasco 500mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-512', 'Solução de mercúrio cromo frasco 500mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-513', 'Solução de permanganato frasco 500mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-514', 'Glutaraldeído 2% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-515', 'Hipoclorito de sódio 1% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-516', 'Peróxido de hidrogênio 3% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-517', 'Peróxido de hidrogênio 10% frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-518', 'Sabão líquido neutro frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-519', 'Desinfetante quaternário frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-520', 'Enzyma desinfetante frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-521', 'Acetona frasco 1L', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-522', 'Cloreto de benzalcônio frasco 500mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-523', 'Sabonete antisséptico líquido 250mL', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-524', 'Toalha para secagem estéril pct', '🧼 ESTERILIZAÇÃO'),
('LAB-EST-525', 'Sachê de enzima desinfetante pct', '🧼 ESTERILIZAÇÃO');

-- 📏 MEDIÇÃO (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-MED-601', 'Pipeta graduada 1 mL', '📏 MEDIÇÃO'),
('LAB-MED-602', 'Pipeta graduada 2 mL', '📏 MEDIÇÃO'),
('LAB-MED-603', 'Pipeta graduada 5 mL', '📏 MEDIÇÃO'),
('LAB-MED-604', 'Pipeta graduada 10 mL', '📏 MEDIÇÃO'),
('LAB-MED-605', 'Pipeta graduada 25 mL', '📏 MEDIÇÃO'),
('LAB-MED-606', 'Pipeta volumétrica 1 mL', '📏 MEDIÇÃO'),
('LAB-MED-607', 'Pipeta volumétrica 2 mL', '📏 MEDIÇÃO'),
('LAB-MED-608', 'Pipeta volumétrica 5 mL', '📏 MEDIÇÃO'),
('LAB-MED-609', 'Pipeta volumétrica 10 mL', '📏 MEDIÇÃO'),
('LAB-MED-610', 'Pipeta volumétrica 25 mL', '📏 MEDIÇÃO'),
('LAB-MED-611', 'Pipeta pasteur 3 mL vidro', '📏 MEDIÇÃO'),
('LAB-MED-612', 'Pipeta pasteur descartável pct', '📏 MEDIÇÃO'),
('LAB-MED-613', 'Ponta para pipeta 10-100 µL caixa', '📏 MEDIÇÃO'),
('LAB-MED-614', 'Ponta para pipeta 100-1000 µL caixa', '📏 MEDIÇÃO'),
('LAB-MED-615', 'Ponta para pipeta 1-10 mL caixa', '📏 MEDIÇÃO'),
('LAB-MED-616', 'Burreta 25 mL', '📏 MEDIÇÃO'),
('LAB-MED-617', 'Burreta 50 mL', '📏 MEDIÇÃO'),
('LAB-MED-618', 'Bureta automática 25 mL', '📏 MEDIÇÃO'),
('LAB-MED-619', 'Microburreta 5 mL', '📏 MEDIÇÃO'),
('LAB-MED-620', 'Pipeta multicanal 12 canais', '📏 MEDIÇÃO'),
('LAB-MED-621', 'Micropipeta 0.5-10 µL', '📏 MEDIÇÃO'),
('LAB-MED-622', 'Micropipeta 10-100 µL', '📏 MEDIÇÃO'),
('LAB-MED-623', 'Micropipeta 100-1000 µL', '📏 MEDIÇÃO'),
('LAB-MED-624', 'Micropipeta 1000-10000 µL', '📏 MEDIÇÃO'),
('LAB-MED-625', 'Suporte universal para pipetas', '📏 MEDIÇÃO');

-- 🛡️ SEGURANÇA (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-SEG-701', 'Extintor de pó ABC 1kg', '🛡️ SEGURANÇA'),
('LAB-SEG-702', 'Extintor de pó ABC 2kg', '🛡️ SEGURANÇA'),
('LAB-SEG-703', 'Extintor de pó ABC 4kg', '🛡️ SEGURANÇA'),
('LAB-SEG-704', 'Extintor de CO2 1kg', '🛡️ SEGURANÇA'),
('LAB-SEG-705', 'Extintor de CO2 2kg', '🛡️ SEGURANÇA'),
('LAB-SEG-706', 'Manta antichama', '🛡️ SEGURANÇA'),
('LAB-SEG-707', 'Kit primeira socorrida comum', '🛡️ SEGURANÇA'),
('LAB-SEG-708', 'Kit primeira socorrida completo', '🛡️ SEGURANÇA'),
('LAB-SEG-709', 'Curativo antisséptico caixa', '🛡️ SEGURANÇA'),
('LAB-SEG-710', 'Gaze estéril 7.5x7.5cm pct', '🛡️ SEGURANÇA'),
('LAB-SEG-711', 'Gaze estéril 10x10cm pct', '🛡️ SEGURANÇA'),
('LAB-SEG-712', 'Atadura elástica 10cm x 3.5m', '🛡️ SEGURANÇA'),
('LAB-SEG-713', 'Atadura elástica 20cm x 3.5m', '🛡️ SEGURANÇA'),
('LAB-SEG-714', 'Esparadrapo 5cm x 10m', '🛡️ SEGURANÇA'),
('LAB-SEG-715', 'Esparadrapo 10cm x 10m', '🛡️ SEGURANÇA'),
('LAB-SEG-716', 'Bandagem triangular pct', '🛡️ SEGURANÇA'),
('LAB-SEG-717', 'Soro fisiológico 0.9% 500mL', '🛡️ SEGURANÇA'),
('LAB-SEG-718', 'Pomada antisséptica tubo', '🛡️ SEGURANÇA'),
('LAB-SEG-719', 'Álcool 70% frasco 500mL', '🛡️ SEGURANÇA'),
('LAB-SEG-720', 'Termômetro clínico digital', '🛡️ SEGURANÇA'),
('LAB-SEG-721', 'Tensiómetro manual', '🛡️ SEGURANÇA'),
('LAB-SEG-722', 'Tensiómetro digital', '🛡️ SEGURANÇA'),
('LAB-SEG-723', 'Oxímetro de pulso', '🛡️ SEGURANÇA'),
('LAB-SEG-724', 'Glucosímetro com lancetas', '🛡️ SEGURANÇA'),
('LAB-SEG-725', 'Placa para sinais de segurança', '🛡️ SEGURANÇA');

-- 🧊 ARMAZENAMENTO (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-ARM-801', 'Frasco vidro transparente 100mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-802', 'Frasco vidro transparente 250mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-803', 'Frasco vidro transparente 500mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-804', 'Frasco vidro âmbar 100mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-805', 'Frasco vidro âmbar 250mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-806', 'Frasco vidro âmbar 500mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-807', 'Frasco plástico com tampa 100mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-808', 'Frasco plástico com tampa 250mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-809', 'Frasco plástico com tampa 500mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-810', 'Frasco plástico com tampa 1000mL', '🧊 ARMAZENAMENTO'),
('LAB-ARM-811', 'Tubo de ensaio com tampa rosca 13mm', '🧊 ARMAZENAMENTO'),
('LAB-ARM-812', 'Tubo de ensaio com tampa rosca 16mm', '🧊 ARMAZENAMENTO'),
('LAB-ARM-813', 'Tubo de ensaio com tampa rosca 20mm', '🧊 ARMAZENAMENTO'),
('LAB-ARM-814', 'Pote redondo 100mL com tampa', '🧊 ARMAZENAMENTO'),
('LAB-ARM-815', 'Pote redondo 250mL com tampa', '🧊 ARMAZENAMENTO'),
('LAB-ARM-816', 'Pote redondo 500mL com tampa', '🧊 ARMAZENAMENTO'),
('LAB-ARM-817', 'Caixa para estocagem pequena', '🧊 ARMAZENAMENTO'),
('LAB-ARM-818', 'Caixa para estocagem média', '🧊 ARMAZENAMENTO'),
('LAB-ARM-819', 'Caixa para estocagem grande', '🧊 ARMAZENAMENTO'),
('LAB-ARM-820', 'Rack para tubos 24 posições', '🧊 ARMAZENAMENTO'),
('LAB-ARM-821', 'Rack para tubos 48 posições', '🧊 ARMAZENAMENTO'),
('LAB-ARM-822', 'Rack para tubos 96 posições', '🧊 ARMAZENAMENTO'),
('LAB-ARM-823', 'Caixa com tampa para slides', '🧊 ARMAZENAMENTO'),
('LAB-ARM-824', 'Cabideiro para prateleira', '🧊 ARMAZENAMENTO'),
('LAB-ARM-825', 'Prateleira metálica ajustável', '🧊 ARMAZENAMENTO');

-- 🧬 DIAGNÓSTICO (25 produtos)
INSERT INTO laboratorio_produtos (codigo, nome, categoria) VALUES
('LAB-DIA-901', 'Swab estéril com tubo caldo 1un', '🧬 DIAGNÓSTICO'),
('LAB-DIA-902', 'Swab estéril com tubo caldo pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-903', 'Swab oral pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-904', 'Swab nasal pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-905', 'Swab faríngeo pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-906', 'Swab genital pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-907', 'Swab oftálmico pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-908', 'Lâmina para microscopia 75x25mm pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-909', 'Lamínula 18x18mm pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-910', 'Lamínula 22x22mm pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-911', 'Lamínula 24x24mm pct', '🧬 DIAGNÓSTICO'),
('LAB-DIA-912', 'Corante Gram frasco 30mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-913', 'Corante Giemsa frasco 30mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-914', 'Corante Ziehl Nielsen frasco 30mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-915', 'Lugol frasco 50mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-916', 'Azul de metileno frasco 30mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-917', 'Fucsina básica frasco 30mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-918', 'Óleo de imersão 50mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-919', 'Solução de NaOH frasco 500mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-920', 'Solução de HCl frasco 500mL', '🧬 DIAGNÓSTICO'),
('LAB-DIA-921', 'Meio de cultura Ágar sangue', '🧬 DIAGNÓSTICO'),
('LAB-DIA-922', 'Meio de cultura Ágar MacConkey', '🧬 DIAGNÓSTICO'),
('LAB-DIA-923', 'Meio de cultura Ágar Sabouraud', '🧬 DIAGNÓSTICO'),
('LAB-DIA-924', 'Meio de cultura Caldo BHI', '🧬 DIAGNÓSTICO'),
('LAB-DIA-925', 'Meio de cultura Tioglicolato', '🧬 DIAGNÓSTICO');

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_laboratorio_produtos_categoria ON laboratorio_produtos(categoria);
CREATE INDEX IF NOT EXISTS idx_laboratorio_produtos_codigo ON laboratorio_produtos(codigo);